name: Deploy to EKS

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Print Environment Variables
      run: env   

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name ora-showroom --debug

    - name: Verify kubectl Access
      run: kubectl get nodes   

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service.yaml  
