name: Deploy to EKS

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Print Environment Variables
      run: env   

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name ora-showroom --debug

    - name: Verify kubectl Access
      run: kubectl get ns  

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: '3.9.0'   

    #- name: Deploy to EKS
    #  run: |
    #    kubectl apply -f k8s/deployment.yaml --validate=false
    #    kubectl apply -f k8s/service.yaml  

    - name: Deploy Helm chart
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update
        helm upgrade --install my-app bitnami/nginx  --namespace ora-default --create-namespace    
